# Generated by Django 4.1.3 on 2023-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
