# Generated by Django 4.1.3 on 2023-09-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0002_studentdetails_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeapp.department'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegeapp.course'),
        ),
    ]
